name: Run JMeter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install JMeter
      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk wget
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xzf apache-jmeter-5.4.1.tgz

      # Step 3: Run JMeter Test
      - name: Run JMeter Test
        run: apache-jmeter-5.4.1/bin/jmeter -n -t test-plan.jmx -l results.jtl -e -o output

      # Step 4: Upload JMeter Results as Artifacts
      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: output

      - name: Deploy JMeter Report to GitHub Pages
        if: success()
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
           git remote add origin https://github.com/Gpsgamers/page.git
           git branch -M main
           git push -u origin main
           ls     
           cp -r output/* .
            rm -rf apache-jmeter-5.4.1
            rm -rf apache-jmeter-5.4.1.tgz
           git add .
           git commit -m "Deploy JMeter report to GitHub Pages"
           git push --force "https://${GH_PAT}@github.com/Gpsgamers/page.git" gh-pages
