name: Run JMeter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run JMeter Test in Docker
      - name: Run JMeter Test in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/jmeter -w /jmeter justb4/jmeter:5.4.1 \
          -n -t test-plan.jmx -l results.jtl -e -o output

      # Step 3: Upload JMeter Results as Artifacts
      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: output
